Add linux-arm64-lts and linux-arm64-musl
prebuild/docker-images pull request #27
Opened 2022-06-26 04:34 UTC by DanSnow

## Description
This PR add two docker images:
- `linux-arm64-lts`: arm64 image with glibc 2.27
- `linux-arm64-musl`: arm64 image with musl as libc

## Context
We are running Node.js on an arm server. But when prebuilding native extension, we encounter the following issue:
- linux-arm64 image has Glibc 2.34, which is higher than the official image on the docker hub (`node:lts-bullseye`), which is 2.31
- no alpine (musl) base image for arm64

2022-06-26 07:15 UTC, vweevers commented
linux-arm64-musl is good to have.

I'm not so sure about linux-arm64-lts. Why is a higher glibc version a problem? Maybe we should fix our existing linux-arm64 image instead. What other differences are there between the two dockcross base images?

2022-06-26 13:42 UTC, DanSnow commented
> Why is a higher glibc version a problem for you?

We tried to use `node:lts-bullseye` as base image. But we got an error like this:
```plain
/lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /path/to/project/node_modules/rocksdb/prebuilds/linux-arm64/node.napi.armv8.node)
```
This is because the glibc version in linux-arm64 is higher then the version in `node:lts-bullseye`. `linux-arm64-lts` will target to a lower version of glibc 2.27 which is compitable with `node:lts-bullseye`.

> Maybe we should fix our existing linux-arm64 image instead

I can modify the PR to use `linux-arm64-lts` as the base image for `linux-arm64`

> What other differences are there between the two dockcross base images?

According to the document for dockcross, the main difference is the version of glibc and gcc

2022-06-26 14:22 UTC, vweevers commented
> I can modify the PR to use linux-arm64-lts as the base image for linux-arm64

Due to the GCC version difference, that might be a breaking change. We can hold off on that for now, keep this PR as-is. At some point I want to align and upgrade GCC versions (https://github.com/prebuild/prebuildify-cross/issues/13), when we get there we'll evaluate whether to keep `linux-arm64-lts`.

2022-06-26 14:23 UTC, vweevers requested changes
Can you please add these new images to the README?

2022-06-27 00:05 UTC, DanSnow commented
@vweevers Added :+1:. Could you take a look?

2022-07-01 11:03 UTC, vweevers approved these changes

2022-07-01 11:03 UTC, merged

2022-07-01 11:15 UTC, vweevers commented
[2.1.0](https://github.com/prebuild/docker-images/releases/tag/v2.1.0)

2022-07-01 11:17 UTC, DanSnow commented
Thanks